quarkus.rest-client."net.opfietse.zrmiles.rest.client.RiderClient".url=http://zrmiles-backend-deployment/api/public
quarkus.rest-client."net.opfietse.zrmiles.rest.client.BikeClient".url=http://zrmiles-backend-deployment/api/public
quarkus.rest-client."net.opfietse.zrmiles.rest.client.RiderBikeClient".url=http://zrmiles-backend-deployment/api/public
quarkus.rest-client."net.opfietse.zrmiles.rest.client.MilesClient".url=http://zrmiles-backend-deployment/api/public

# For running behind reverse proxy
quarkus.http.proxy.proxy-address-forwarding=true
quarkus.http.proxy.allow-x-forwarded=true
quarkus.http.proxy.enable-forwarded-host=true
quarkus.http.proxy.enable-forwarded-prefix=true

%dev.quarkus.http.proxy.proxy-address-forwarding=true
%dev.quarkus.http.proxy.allow-forwarded=true
#%dev.quarkus.http.proxy.allow-x-forwarded=true
#%dev.quarkus.http.proxy.enable-forwarded-host=true
#%dev.quarkus.http.proxy.enable-forwarded-prefix=true
#%dev.quarkus.http.proxy.trusted-proxies=127.0.0.1
#%dev.quarkus.http.root-path=/zrmiles-new

backend-server=localhost:8081
%dev.quarkus.rest-client."net.opfietse.zrmiles.rest.client.RiderClient".url=http://${backend-server}/api/public
%dev.quarkus.rest-client."net.opfietse.zrmiles.rest.client.BikeClient".url=http://${backend-server}/api/public
%dev.quarkus.rest-client."net.opfietse.zrmiles.rest.client.RiderBikeClient".url=http://${backend-server}/api/public
%dev.quarkus.rest-client."net.opfietse.zrmiles.rest.client.MilesClient".url=http://${backend-server}/api/public

# Configure OIDC
quarkus.oidc.auth-server-url=https://www.opfietse.net/auth/realms/zrmiles
quarkus.oidc.client-id=zrmiles-frontend
#quarkus.oidc.credentials.secret=secret

# Tell Dev Services for Keycloak to import the realm file
# This property is ineffective when running the application in JVM or Native modes but only in dev and test modes.

#quarkus.keycloak.devservices.realm-path=quarkus-realm.json

# Configure OIDC Client
quarkus.oidc.application-type=web-app
quarkus.oidc-client.auth-server-url=${quarkus.oidc.auth-server-url}
quarkus.oidc-client.client-id=${quarkus.oidc.client-id}
quarkus.oidc-client.grant.type=password
quarkus.oidc-client.grant-options.password.username=alice
quarkus.oidc-client.grant-options.password.password=alice

quarkus.http.auth.permission.service.paths=/*
quarkus.http.auth.permission.service.policy=authenticated

quarkus.http.auth.permission.oidcproxy.paths=/zrmiles/q/*
quarkus.http.auth.permission.oidcproxy.policy=permit
