apiVersion: v1
kind: PersistentVolume
metadata:
  name: maven-nfs
spec:
  storageClassName: nfs
  capacity:
    storage: 10G
  accessModes:
    - ReadWriteOnce
  nfs:
    server: kube05
    path: "/home/rvk/nfs/maven"
  mountOptions:
    - nfsvers=4.2
