apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "zrmiles-frontend-kaniko-job.fullname" . }}
  labels:
    {{- include "zrmiles-frontend-kaniko-job.labels" . | nindent 4 }}
spec:
{{/*  selector:*/}}
{{/*    matchLabels:*/}}
{{/*      {{- include "build-job.selectorLabels" . | nindent 6 }}*/}}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "zrmiles-frontend-kaniko-job.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "zrmiles-frontend-kaniko-job.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      restartPolicy: Never
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
{{/*          ports:*/}}
{{/*            - name: http*/}}
{{/*              containerPort: {{ .Values.service.port }}*/}}
{{/*              protocol: TCP*/}}
{{/*          livenessProbe:*/}}
{{/*            {{- toYaml .Values.livenessProbe | nindent 12 }}*/}}
{{/*          readinessProbe:*/}}
{{/*            {{- toYaml .Values.readinessProbe | nindent 12 }}*/}}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          args:
            - "--dockerfile=src/main/docker/Dockerfile.jvm-rpi"
            - "--context=dir:///src/zrmiles-backend"
            - "--destination={{ .Values.app.image_name}}:{{ .Values.app.image_tag}}"
            - "--insecure"
          {{- with .Values.env }}
          env:
            {{- toYaml . | nindent 10 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
